config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'why', to: 'home#why', as: 'why'
  get 'contact', to: 'home#contact', as: 'contact'

  # feelings routes
  post 'feeling', to: 'feelings#create'

  # session routes
  post 'session/create', to: 'sessions#create'
  put 'session/end', to: 'sessions#end'

  # stats routes
  get 'stats/current_sessions', to: 'stats#current_sessions'
  get 'stats/feelings_today', to: 'stats#feelings_today'
  get 'stats', to: 'stats#stats'
  
end

app/models/feeling.rb
class Feeling < ActiveRecord::Base
  belongs_to :session
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_many :feelings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController

  def create
    session = Session.find(params[:session_id])
    session_finished = !session.end_time.nil?
    last_feeling = session.feelings.last

    if session_finished || (session.created_at < 5.minutes.ago && last_feeling.nil?)
      if !session_finished
        session.destroy
      end
      @session = Session.create.id
      Feeling.create(text: params[:text], session_id: params[:session_id])
    elsif last_feeling.nil? || last_feeling.created_at > 5.minutes.ago
      Feeling.create(text: params[:text], session_id: params[:session_id])
      @session = params[:session_id].to_i
    else
      session.update(end_time: last_feeling.created_at)
      @session = Session.create.id
      Feeling.create(text: params[:text], session_id: @session)
    end
    render json: { id: @session }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def why
  end

  def contact
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @session = Session.create
    render json: { id: @session.id}
  end

  def end
    @session = Session.find_by(id: params[:session_id], end_time: nil)
    @feeling = @session.feelings.last
    if @feeling.nil?
      @session.destroy
    else
      @session.update(end_time: @feeling.created_at)
    end
    render nothing: true
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  # Useful if you need to convert time into string in controller
  include ActionView::Helpers::DateHelper

  def feelings_today
    @feelings = Feeling.where('created_at >= ?', 24.hours.ago).count
    render json: { count: @feelings}
  end

  def current_sessions
    @sessions = Session.where(end_time: nil).count
    render json: { count: @sessions}
  end

  def stats
    periods = ['day', 'week', 'month']
    @stats = periods.inject([]) do |memo, period|
      memo << get_stats(period)
    end
  end

  private

  def get_stats(period)
    sessions = Session.where('created_at >= ?', Time.zone.now.send("#{period}s_ago",1))
                      .where.not(end_time: nil)
    feelings = Feeling.joins(:session).where('sessions.created_at >= ?', Time.zone.now.send("#{period}s_ago",1))
                      .where.not(sessions: {end_time: nil}).count
    
    # session stats
    s_count = sessions.count
    s_time =  sessions.sum('extract(epoch from end_time - created_at)').to_i
    # s_average = distance_of_time_in_words(s_time / s_count)
    s_time = distance_of_time_in_words(s_time)

    # feeling stats
    f_count = feelings

    results = { text: text_helper(period),
                s_count: s_count, 
                s_time: s_time, 
                # s_average: s_average,
                f_count: f_count,
                # f_average: f_count / s_count 
              }
  end

  def text_helper(period)
    if period == "day"
      result = "In the past 24 hours"
    elsif period == "week"
      result = "In the past 7 days"
    elsif period == "month"
      result = "In the past 30 days"
    end
    result
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.erb
<div class="row">
	<div class="col s10">
		<input type="text" placeholder="How are you feeling?">
	</div>
	<div style="padding-top:15px;" class="col s2">
		<div class="icons right">
			<i class="material-icons delete">delete</i>
			<i class="material-icons add">add_circle</i>
		</div>
	</div>
</div>

app/views/home/contact.html.erb
<div class="container">
	<div class="row">
		<div class="col s12 center-align">
			<h1 style="padding-top: 50px;">Please contact me at</h1>
			<p class="flow-text"> rickard.sunden@outlook.com</p>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<div id="welcome" class="container">
  <div class="row">
    <div class="col s12 center-align">
      <h1> How are you feeling? </h1>
      <p class="flow-text"> Click the button below to get started.</p>
      <a id="trigger-modal" class="btn-floating btn-large modal-trigger" href="#feelings-modal"><i class="material-icons">edit</i></a>
    </div>
  </div>	
</div>

<!-- Modal Structure -->
<div id="feelings-modal" class="modal">
  <div class="modal-content">
    <form id="feelings-input">
      <div class="row">
        <div class="col s12">
         <p>Type however you're feeling, it could be feelings like "i'm so lonely", "i hate mondays".</p>
        </div>
      </div>
      <div class="row">
        <div class="col s10">
          <input type="text" placeholder="How are you feeling?">
        </div>
        <div style="padding-top:15px;" class="col s2">
          <div class="icons right">
            <i class="material-icons add">add_circle</i>
          </div>
        </div>
      </div>
    </form>
    <div class="modal-footer center-align">
      <a id="form-submission" class="modal-action btn">Ok time to pop!</a>
    </div>
  </div>
</div>

<div class="canvas-container" style="display:none;">
  <canvas id="myCanvas" style="display:none;" resize="true"></canvas>
</div>

<script>
// Setup the modal trigger to work

$(document).ready(function(){
  // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
  $('.modal-trigger').leanModal();
});

</script>

<script type="text/paperscript" canvas="myCanvas">

// GLOBAL VARIABLES

var feelings = [];
var session_id;
var sound = true;
var audio = new Audio('blop.mp3');
var feelingsCount = 0;

//
// FUNCTIONS FOR FORM
//

// DELETING INPUT

$('form').on( "click", '.material-icons.delete', function() {
  $(this).closest('.row').slideUp(200, function(){ 
    $(this).remove();
    if( $('form .icons:last-child .material-icons.add').last().length === 0 ){
      $('form .row:last-child .icons.right').append('<i class="material-icons add">add_circle</i>');
    }
  });
});

// ADDING INPUT

$('form').on( "click", '.material-icons.add', function() {
  $(this).remove();
  $("<%= escape_javascript(render partial: 'form') %>").appendTo('form').hide().slideDown(200);
});

// PREVENTING PRESSING ENTER

$(document).ready(function() {
  $('.modal input').keydown(function(event){
    if(event.keyCode == 13) {
      triggerGame();
      event.preventDefault();
    }
  });
});

// SUBMITTING THE FORM

$( "#form-submission" ).on('click', function(event) {
  triggerGame();
  event.preventDefault();
});

// WILL SET OFF THE TRIGGER FOR THE GAME

function triggerGame(){
  var filledOut;
  feelings = []
  $('#feelings-input').find('input').each(function () {
    if($(this).val() === ""){
      $(this).attr("placeholder", "Hey this can't be empty!");
      filledOut = false;
      return false;
    }
    else {
      filledOut = true;
      feelings.push(this.value);
    }
  });
  if(filledOut){
    $('#feelings-modal').closeModal();
    game();
  }
}

//
// MODAL STUFF
//

// STARTING UP THE MODAL

$('#trigger-modal').click(function(){
  if($(this).hasClass('modal-nav') === false){
    var clone = $(this).clone();
    $(this).closest('.container').fadeOut(100, function(){
      $(this).closest('.container').remove();
      var new_button = $('<li><a id="trigger-modal" class="modal-trigger" href="#feelings-modal"><i class="material-icons">edit</i></a></li>').prependTo('#right-links').hide();
      $(new_button).addClass('modal-nav')
      $(new_button).fadeIn(100);
      $('.modal-trigger').leanModal();
    });
  }
});

//
// SOUND STUFF
//

// ADDING SOUND LINK TO THE RIGHT LINKS IN NAVBAR

$('#right-links').append('<li><a id="sound"><i class="material-icons">volume_up</i></a></li>');


// MUTING AND UNMUTING THE GAME

$('#sound').click(function(event){
  sound = !sound;
  if(sound){
    $(this).html('<i class="material-icons">volume_up</i>');
  }
  else {
    $(this).html('<i class="material-icons">volume_off</i>');
  }
  event.preventDefault();
});

// ADDING CURRENT FEELINGS COUNT

// $(document).ready(function(){
//   $('#count-links').prepend('<li><a id="feelings-count" href="#"><i class="material-icons left">cloud_upload</i><span>0</span></a></li>');
// })

// function update_count(count, id){
//   var oldCount = +$("#"+id +' span').text();
//   if (count !== oldCount){
//     $("#"+id +' span').text(count);
//   }
// }

// ENDING THE SESSION

$( window ).unload(function() {
  clearInterval(timer)
  if (session_id !== undefined){
   $.ajax({
     url: "/session/end",
     method: "PUT",
     async: false,
     data: { session_id: session_id}
   });
 }
});

var destination = Point.random() * view.size;
var paused = true;
var gameCount = 0;


// Give the canvas a width and height

$(document).ready(function(){
  $('.canvas-container').height($(window).height() - $('nav').height());
  $('.canvas-container').width($(window).width());
  view.viewSize.width =  $('.canvas-container').width();
  view.viewSize.height =  $('.canvas-container').height();
 });

$(window).resize(function(){
  $('.canvas-container').height($(window).height() - $('nav').height());
  $('.canvas-container').width($(window).width());
  view.viewSize.width =  $('.canvas-container').width();
  view.viewSize.height =  $('.canvas-container').height();
});



function game(){
  // make sure the view size is correct
  view.viewSize.width =  $('.canvas-container').width();
  view.viewSize.height = $('.canvas-container').height();
  if(session_id === undefined) {
   $.ajax({
    url: "/session/create",
    method: "POST",
    data: {},
    dataType: "json",
    success: function ( msg ) {
      session_id = msg.id;
    }
   });
  }
  paused = false;
  if(gameCount > 0){
    project.activeLayer.lastChild.remove();
  }
  $('.canvas-container').show();
  $('canvas').show();
  createCloud();
  gameCount += 1;
}

function createCloud(){
  // group to combine text and cloud
  group = new Group();
  
  // starting points of the group
  var point = Point.random()*view.size;

  // Add the text for the cloud first to calculate width
  var text = new PointText();
  text.justification = 'center';
  text.fillColor = '#34495e';
  text.content = randomArray(feelings);
  text.fontSize = 14;
  group.addChild(text);
  // hide the text for now just to be safe
  text.visible = false;
  
  // create the cloud
  // path for cloud below
  var pathData = 'M -25,-20 a 20,20 1 0,0 0,40 h 50 a 20,20 1 0,0 0,-40 a 10,10 1 0,0 -15,-10 a 15,15 1 0,0 -35,10 z';
  var path = new Path(pathData); 
  path.fillColor = '#ecf0f1'
  path.position = new Point(point['x'],point['y']);
  path.insertBelow(text);
  
  // putting it all together
  // change the size of the cloud to fit the text width
  var scale = cloudScale(text.bounds.width);
  path.scale(scale)
  // center the text vertically in the  cloud
  text.position = new Point(point['x'], point['y'] + centerText(scale));
  text.visible = true;
  
  group.onMouseDown = function(event) {
    // feelingsCount += 1;
    // update_count(feelingsCount,'feelings-count')
    if (sound){
      audio.play();
    }
    $.ajax({
      url: "/feeling",
      method: "POST",
      data: { session_id : session_id },
      dataType: "json",
      success: function ( msg ) {
        session_id = msg.id;
      }
    });
    this.remove();
    destination = Point.random() * view.size;
    createCloud();
  }
}

function onFrame(event) {
  if(!paused){
    var vector = destination - project.activeLayer.lastChild.position;
    project.activeLayer.lastChild.position += vector / 100;
    // var topDistance = project.activeLayer.lastChild.bounds.top
    if (vector.length < 5) {
      destination = Point.random() * view.size;
    }
  }
}

function centerText(scale){
  // center the text vertically in the cloud
  return scale * 11
}

function cloudScale(textWidth){
  // constant based on a padding for text that looked good
  var scale = textWidth * 0.01416712819;
  if(scale <= 0.8){ scale = 0.8; }
  return scale;
}

function randomArray(array){
 return array[Math.floor(Math.random()*array.length)];
}

</script>

app/views/home/why.html.erb
<div class="container">
<div class="row">
    <div class="col s8 offset-s2 center-align">
      <h1 style="padding-top: 50px;">Pop bad feelings.</h1>
      <p class="flow-text"> 
          Did you have a tough day? Are you feeling sad, stressed, or mad about something?
       </p>
        <p class="flow-text"> 
          All you have to do is type what you're feeling: "I want to give up", "I don't want to go school", "I hate myself". Then just pop away until you feel better or you get bored.
       </p>
    </div>
	<div class="row">
		<div class="col s8 offset-s2 center-align">
			<h1>Free from judgment.</h1>
			<p class="flow-text"> 
        No one will ever see what you type here. Theres no one here to tell you how you should feel, its just you and your computer screen. Everything here is private and anonymous.
       </p>
		</div>
	</div>
    <div class="row">
    <div class="col s8 offset-s2 center-align">
      <h1>You're not alone.</h1>
      <p class="flow-text">
        Have a look in the top right corner of your screen and you'll see that other people are feeling bad just like you. I just want you to know you're not alone in your suffering. Please find someone to talk to help you feel better.
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Popthatfeeling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body style="display:none;">
  <nav>
   <div class="nav-wrapper">
      <a data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>

     
    <ul id="right-links" class="right">
    </ul>
    <ul id ="count-links" class="right">
      <li><a id="cloud" class="tooltipped" data-position="left" data-delay="50" data-tooltip="Feelings popped in the past 24 hours:"><i class="material-icons left">cloud</i><span>0</span></a></li>
      <li><a id="person" class="tooltipped" data-position="left" data-delay="50" data-tooltip="People popping feelings right now:"><i class="material-icons left">person</i><span>0</span></a></li>
    </ul>

    

    <ul id="slide-out" class="side-nav">
      <li><%= link_to 'popthatfeeling', root_path %></li>
      <li><%= link_to 'why', why_path %></li>
      <li><%= link_to 'stats', stats_path %></li>
      <li><%= link_to 'contact', contact_path %></li>
    </ul>
  
    </div>
  </nav>
  
<%= yield %>

  <script>
  	$(".button-collapse").sideNav();
  </script>

</body>
</html>

app/views/stats/stats.html.erb
<div class="container">
	<div class="slider">
		<ul class="slides">
			<% @stats.each do |stat| %>
				<li>
					<!-- Slider doesn't work unless there is an image -->
					<img src="">
					<div class="caption center-align">
						<h1><%= stat[:text] %></h1>
						<p class="flow-text"><%= number_with_delimiter(stat[:s_count], delimiter: ',') %> people have spent <%= stat[:s_time] %> popping their bad feelings. Together we popped <%= number_with_delimiter(stat[:f_count], delimiter: ',') %> feelings.</p>
						<p class="flow-text"> </p>
						<% if stat[:s_count] > 1 && stat[:f_count] > 1 %>
							<h4> You're not alone. </h4>
						<% end %>
					</div>
				</li>
			<% end %>
		</ul>
	</div>
</div>

<script>

	$(document).ready(function(){
      $('.slider').slider({interval: 15000, transition: 1000});
    });
        
</script>